run:
  script:
    - whoami  
    - cd /home/dmitry/back/
    - git fetch git@stavteam2020.ddns.net:ld/stavteamback.git
    - gil pull git@stavteam2020.ddns.net:ld/stavteamback.git
    - systemctl restart stavteamback
